name: Build setup wizard

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag for the release (e.g., v4.0.0.0)"
        required: true
      release_name:
        description: "Name of the release (defaults to the tag)"
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and install Inno Setup 6.4.3
        working-directory: ./app
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.4.3.exe" -OutFile is.exe
          Start-Process -FilePath ".\is.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART" -Wait
          Remove-Item .\is.exe

      - name: Build installer with Inno Setup
        working-directory: ./app
        shell: cmd
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" RCC3_Installer.iss

      - name: Generate SHA-256 hash
        working-directory: ./app
        shell: pwsh
        run: |
          $installer = Get-ChildItem .\RCC3_Installer*.exe | Select-Object -First 1
          if ($installer) {
            $hash = Get-FileHash $installer.FullName -Algorithm SHA256 | Select-Object -ExpandProperty Hash
            Set-Content -Encoding ASCII -Path RCC3_Installer.exe.sha256 -Value $hash
          }

      - name: Create GitHub Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_name || github.event.inputs.tag_name }}
          generate_release_notes: true
          files: |
            app/RCC3_Installer*.exe
            app/RCC3_Installer.exe.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
