name: Build rcur_importer_launcher

permissions:
  contents: write

on:
  push:
    paths:
      - 'app/rcur_importer_launcher.cpp'
      - 'app/rcur_importer_launcher.iss'
  pull_request:
    paths:
      - 'app/rcur_importer_launcher.cpp'
      - 'app/rcur_importer_launcher.iss'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up MSVC (Developer Command Prompt)
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build C++ launcher
        working-directory: ./app
        run: cl rcur_importer_launcher.cpp /O2 /link shell32.lib /SUBSYSTEM:WINDOWS /INCREMENTAL:NO

      - name: Download and install Inno Setup 6.4.3
        working-directory: ./app
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.4.3.exe" -OutFile is.exe
          Start-Process -FilePath ".\is.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART" -Wait
          Remove-Item .\is.exe

      - name: Build installer with Inno Setup
        working-directory: ./app
        run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" rcur_importer_launcher.iss'

      - name: Generate SHA-256 hashes
        working-directory: ./app
        shell: pwsh
        run: |
          Get-FileHash .\rcur_importer_launcher.exe -Algorithm SHA256 | Select-Object -ExpandProperty Hash | Out-File -Encoding ASCII -Force rcur_importer_launcher.exe.sha256
          $installer = Get-ChildItem .\Output\*.exe | Select-Object -First 1
          if ($installer) {
            Get-FileHash $installer.FullName -Algorithm SHA256 | Select-Object -ExpandProperty Hash | Out-File -Encoding ASCII -Force RCC3_Installer.exe.sha256
            Copy-Item $installer.FullName RCC3_Installer.exe -Force
          }

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push EXEs and hashes
        shell: pwsh
        run: |
          $branch = "${{ github.ref }}" -replace '^refs/heads/', ''
          git add -f app/rcur_importer_launcher.exe
          git add -f app/rcur_importer_launcher.exe.sha256
          git add -f app/RCC3_Installer.exe
          git add -f app/RCC3_Installer.exe.sha256
          git commit -m "chore: build and package launcher + installer [skip ci]" || echo "No changes to commit"
          git push origin $branch || echo "Nothing to push"
